#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := oled

INCLUDE = -I $(PROJECT_PATH)/main/OLED

include $(IDF_PATH)/make/project.mk

